name: Run Tests

on:
  push:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: microsoft
        cache: gradle
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Run tests
      run: gradle test
      
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          build/test-results/test/*.xml
